name: Build and Upload to TestPyPI

on:
  push:
    branches:
      - main  # or your default branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Ensure this matches your project's required Python version

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
      working-directory: ./packaging_tutorial  # Adjust this to the correct subdirectory

    - name: Build package
      run: |
        python -m build
      working-directory: ./packaging_tutorial  # Adjust this to the correct subdirectory

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: built-packages
        path: ./packaging_tutorial/dist/*  # Correct path to the dist folder

    - name: Publish to TestPyPI
      env:
        TWINE_USERNAME: "__token__"  # Special username for token-based auth
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}  # Use the secret stored in GitHub
      run: |
        python -m twine upload --repository testpypi dist/* --verbose
      working-directory: ./packaging_tutorial  # Adjust this to the correct subdirectory
